name: Build and Release Clood

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

#      - name: Test
#        run: dotnet test --no-restore --verbosity normal

      - name: Publish Single File Executable
        run: |
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -o ./publish/win-x64
          dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true -o ./publish/linux-x64
          dotnet publish -c Release -r osx-x64 -p:PublishSingleFile=true --self-contained true -o ./publish/osx-x64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Zip Release
        run: |
          zip -r clood-win-x64.zip ./publish/win-x64
          zip -r clood-linux-x64.zip ./publish/linux-x64
          zip -r clood-osx-x64.zip ./publish/osx-x64

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./clood-win-x64.zip
          asset_name: clood-win-x64.zip
          asset_content_type: application/zip

      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./clood-linux-x64.zip
          asset_name: clood-linux-x64.zip
          asset_content_type: application/zip

      - name: Upload macOS Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./clood-osx-x64.zip
          asset_name: clood-osx-x64.zip
          asset_content_type: application/zip