name: Build and Release Clood
on:
  push:
    branches:
      - main-clood-keys
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOODKEY: ${{ secrets.CLOODKEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Set up .NET user secrets
        run: |
          dotnet user-secrets init --project CloodAndFriends/Clood
          dotnet user-secrets set "clood-key" "$CLOODKEY" --project CloodAndFriends/Clood
          dotnet user-secrets init --project CloodAndFriends/Clood.Test
          dotnet user-secrets set "clood-key" "$CLOODKEY" --project CloodAndFriends/Clood.Test
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal